/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export class ErrorDto {
   key?: string | undefined;
   value?: string | undefined;

}

export abstract class OrderAddressBase {
   name!: string;
   firstLine!: string;
   secondLine?: string | undefined;
   city!: string;
   postcode!: string;

}

export class Address extends OrderAddressBase {
   id?: number;
   isDefault?: boolean;
   instructions?: string | undefined;
   userId?: number;

}

export class LoginInfo {
   email?: string | undefined;
   password?: string | undefined;
   rememberMe?: boolean;

}

export class ExternalLoginInfo {
   code!: string;
   state!: string;
   type?: RegistrationTypes;
   rememberMe?: boolean;
   redirectUrl?: string | undefined;

}

export enum RegistrationTypes {
   Application = 0,
   Google = 1,
   Facebook = 2,
   Github = 3,
}

export class Category {
   id?: number;
   name!: string;
   imagePath?: string | undefined;
   originalImagePath?: string | undefined;
   imageBase64!: string;
   originalImageBase64!: string;
   totalProducts?: number;

}

export class ResultListOfCategory {
   list?: Category[] | undefined;
   totalCount?: number;

}

export class Coupon {
   code!: string;
   pendigCode?: string | undefined;
   type!: CouponType;
   maxUseQuantity?: number;
   discountAmount?: number;
   expiryDate!: Date;

}

export enum CouponType {
   FreeDelivery = 0,
   DiscountPrice = 1,
   PercentageOfTotal = 2,
}

export class EmailTemplate {
   id?: number;
   name!: string;
   subject!: string;
   tokenUrlPath?: string | undefined;
   serverVariables?: ServerVariables[] | undefined;
   locked?: boolean;
   isDefaultTemplate?: boolean;
   html!: string;
   design!: any;

}

export class ServerVariables {
   id?: number;
   enumValue!: EmailTemplateServerVariables;
   replacementValue!: string;

}

export enum EmailTemplateServerVariables {
   UserName = 0,
   RegistrationMethod = 1,
   Role = 2,
   TokenUrl = 3,
   ExpiaryDateTime = 4,
}

export class Newsletter {
   email!: string;
   displayName?: string | undefined;

}

export class Order extends OrderAddressBase {
   id?: number;
   date?: Date;
   status!: OrderStatusType;
   deliveryOption!: DeliveryOption;
   totalPrice?: number;
   deliveryPrice?: number;
   address!: Address;
   payment!: Payment;
   coupon?: Coupon | undefined;
   orderItems?: OrderItem[] | undefined;

}

export enum OrderStatusType {
   Placed = 0,
   Hold = 1,
   Confirmed = 2,
   Delivered = 3,
   Canceled = 4,
}

export class DeliveryOption {
   id?: number;
   name!: string;
   price!: number;
   minimumOrderTotal!: number;

}

export class Payment {
   id?: number;
   paymentProvider!: string;
   reference!: string;
   dateTime!: Date;

}

export abstract class OrderProductBase {
   name!: string;
   price!: number;
   unitQuantity!: number;
   unitType!: ProductUnitType;

}

export class OrderItem extends OrderProductBase {
   id?: number;
   productCategoryName!: string;
   productId?: number | undefined;
   quantity!: number;

}

export enum ProductUnitType {
   Kg = 0,
   Grams = 1,
   Per_Item = 2,
}

export class Product extends OrderProductBase {
   id?: number;
   description?: string | undefined;
   imagePath?: string | undefined;
   originalImagePath?: string | undefined;
   imageBase64!: string;
   originalImageBase64!: string;
   status?: boolean;
   category!: Category;
   nutritionalInfo?: NutritionalInfo | undefined;
   comments?: Comment[] | undefined;
   scores?: Score[] | undefined;
   averageScore?: number;

}

export class NutritionalInfo {
   id?: number;
   perGram?: number;
   energyKJ?: number | undefined;
   energyKcal?: number | undefined;
   fat?: number | undefined;
   saturateFat?: number | undefined;
   carbohydrate?: number | undefined;
   carbohydrateSugar?: number | undefined;
   fibre?: number | undefined;
   protein?: number | undefined;
   salt?: number | undefined;

}

export class Comment {
   id?: number;
   description!: string;
   orderItem?: OrderItem | undefined;
   orderItemId?: number;
   product?: Product | undefined;

}

export class Score {
   id?: number;
   rate?: number;
   orderItem?: OrderItem | undefined;
   orderItemId?: number;
   product?: Product | undefined;

}

export class IdentityUserOfInteger {
   id?: number;
   userName?: string | undefined;
   normalizedUserName?: string | undefined;
   email?: string | undefined;
   normalizedEmail?: string | undefined;
   emailConfirmed?: boolean;
   passwordHash?: string | undefined;
   securityStamp?: string | undefined;
   concurrencyStamp?: string | undefined;
   phoneNumber?: string | undefined;
   phoneNumberConfirmed?: boolean;
   twoFactorEnabled?: boolean;
   lockoutEnd?: Date | undefined;
   lockoutEnabled?: boolean;
   accessFailedCount?: number;

}

export class User extends IdentityUserOfInteger {
   firstName!: string;
   surname!: string;
   role!: Role;
   phoneNumber?: string | undefined;
   registrationMethod!: RegistrationMethod;
   email!: string;
   addresses?: Address[] | undefined;
   password?: string | undefined;
   subscribeNewsLetter?: boolean;

}

export class Role {
   id?: number;
   name!: string;
   accessClaim!: string;

}

export class RegistrationMethod {
   externalLinkedId?: string | undefined;
   type!: RegistrationTypes;
   registeredDate?: Date;

}

export class UpdateCurrentUserData {
   user?: User | undefined;
   currentPassword?: string | undefined;

}